### ISSUE TITLE
Minutes in the 2021 folder are labelled with a 2020 date

### ISSUE THREAD

**Issue by GenevieveBuckley** [napari/meeting-notes#17]
Why are there several meeting minutes labelled "2020" in the 2021 folder? What's going on with these? https://github.com/napari/meeting-notes/tree/main/2021

I think those dates are wrong, and that they're probably meant to say 2021 instead, based on when these files were created (between 4 and 10 months ago).

- `2020-01-14.md`: Create 2020-01-14.md 10 months ago
- `2020-01-21.md`: Create 2020-01-21.md 10 months ago
- `2020-06-24.md`: Create 2020-06-24.md 4 months ago
- `2020-11-10-euro-NA.md`: Create 2020-11-10-euro-NA.md 15 hours ago 

@sofroniewn and @alisterburt, looks like you both uploaded some of these files. Can you confirm whether the dates need fixing (in filenames and file text), or if they're in the wrong spot.

**Comment by sofroniewn** [comment]
Those are definitely mistakes/ typos. I think it is because the autocomplete puts in 2020 dates and then maybe I/ we forget to change them!

I have changed all four of those and so I think we can close this issue, but if i've done anything wrong/ made a mistake we can reopen. Thanks for catching and flagging @GenevieveBuckley!!

**Comment by alisterburt** [comment]
Thanks for catching @GenevieveBuckley, definitely a mistake on my end. ThNks for catching and thanks for updating @sofroniewn !
